### ISSUE TITLE
RoR group project: set up your Kanban board [0.5pts]

### ISSUE THREAD

**Issue by shafiuyushawu** [shafiuyushawu/recipe-app#10]
Hi Reviewer,

This is @shafiuyushawu and @zdnahom, we are partners for this week group project, and this milestone of the project fulfills the following requirements;

## Project requirements ♻️ 
- Create an empty repository for your group project.
- Open the GitHub project (Kanban board) in your team repo (set up the same columns as in previous group projects).
- Open [project requirements](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/buisness_requirements.md) and read them carefully.
- Create tasks on your Kanban board based on the [project requirements](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/buisness_requirements.md).
- Each task should be a separate card that:
  - Has a descriptive title.
  - Has the number of points in the [Xpt] prefix. That number should indicate the number of points that show how complex the task is. 1 point = 1 hour of estimated work. You shouldn't change the points after dividing up cards, even if the actual work takes longer.
  - Has a description of the task.
- Each of the team members should assign themselves to the cards (and time estimate distributions should be fair - no single person should be doing all of the most time-consuming tasks). Decide who will be the assignee for the cards marked as group tasks. All cards on your Kanban board should have assignees.

- Kind find the [project link here](https://github.com/users/shafiuyushawu/projects/11/views/1)

**Comment by mckent05** [comment]
Hi team, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/207265056-d056ea78-77c5-4b66-802e-694a5ed4ecf3.gif)

## Highlights
- All tasks have been fairly assigned ✔️ ✔️ 
- Good job setting up your Kanban board 👍 👍 


## Required Changes ♻️
- According to the project requirements, all project tasks should have a task card in the Kanban board, currently some project tasks have no task card.
- - `You should follow the layout of the wireframes provided. You should personalize the rest of the design including colors, typographies, spacings, etc.`
- - `Food list (only for a group that has less than 3 members):
           Should display a list of food added by the logged-in user as in the wireframe (display also quantity of a given food).
           Should lead to a form that allows users to add new food.`
- Also, according to the project requirements, all tasks card should have a card description, some of your cards have missing descriptions, please fix this 🙏 
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by shafiuyushawu** [comment]
Hello @mckent05,
Thanks for the pin points we really appreciate them, the required changes have been resolved.

**Comment by rloterh** [comment]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted this project under the wrong activity, _**RoR group project: day 3**_ instead of _**RoR group project: set up your Kanban board**_. Let's resubmit this project under the correct activity.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by mckent05** [comment]
Hi team, 

# STATUS: APPROVED ✔️ ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to start your capstone :shipit: 
Congratulations and well done! 🎉 
![approved](https://user-images.githubusercontent.com/73607512/207264357-1b05ce6a-95f2-4d31-9c26-888c6ddfa124.gif)


## Highlights
- All tasks have been fairly assigned ✔️ ✔️ 
- You have correctly setup your Kanban board 👏 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
